# -*- coding: utf-8 -*-
iloscbazy = int(input("Podaj objętość premixu (ml):\n"))
mocbazy = float(input("Podaj moc premixu (mg/ml):\n"))
iloscshota = int(input("Podaj objętość shotów (ml):\n"))
mocshota = float(input("Podaj moc shotów (mg/ml):\n"))
iloscwynikowa = int(iloscbazy+iloscshota)
mocpremix = float(mocbazy*iloscbazy)
moctemp = float(mocshota*iloscshota)
mocwynikowa = float(mocpremix+moctemp)
mocwynikowa = float(mocwynikowa/iloscwynikowa)
print("Objętość liquidu: %s"%iloscwynikowa)
print("(ml)\n")
print("Moc liquidu: %10.2f"%mocwynikowa)
print("(mg/ml)\n")
